project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "notebooks/random-walk-prior.qmd"
    - "notebooks/robust-errors.qmd"
    - "notebooks/mann-whitney-u.qmd"
    - "notebooks/custom-distribution-stan.qmd"
    - "notebooks/door-1.qmd"
    - "notebooks/probabilistic-index.qmd"
    - "notebooks/hypothetical-estimands.qmd"
    - "notebooks/limits-of-per-protocol.qmd"
    - "notebooks/multinomial-regression.qmd"
    - "notebooks/principal-stratification.qmd"
    - "notebooks/graphviz.qmd"
    - "notebooks/covid-19-vaccine-efficacy.qmd"
    - "notebooks/discrete-parameters-stan.qmd"

highlight-style: github
link-citations: true

website:
  title: "maj-biostat.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



