project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!notebooks-drafts/*.*"

execute:
  freeze: true
  
highlight-style: github
link-citations: true

website:
  title: "maj-biostat.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/maj-biostat/maj-biostat.github.io
  search: 
    location: navbar
    type: overlay

format:
  html:
    fontsize: 10pt
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    execute:
      freeze: auto  #re-render only when source changes



