project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "maj-biostat.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  search: 
    location: navbar
    type: overlay
  reader-mode: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



