project:
  type: website
  output-dir: docs
  execute-dir: project

highlight-style: github
link-citations: true

website:
  title: "maj-biostat.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



